---
name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild
        uses: robertdebock/rpmbuild-action@1.0.0
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: rpm
          path: RPMS/x86_64/my-1.0.0-0.x86_64.rpm
