---
name: Build RPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rpmbuild
        uses: robertdebock/rpmbuild-action@1.0.0
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: RPMS/x86_64/my-1.0.0-0.x86_64.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: Upload math result for job 1
#         uses: actions/upload-artifact@v1
#         with:
#           name: rpm
#           path: RPMS/x86_64/my-1.0.0-0.x86_64.rpm
